[package]
name = "rusty_trace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
sdl2 = "0.35.2"
image = "0.24.5"
anyhow = "1.0.69"
